config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'weather_forecasts#index'
  get '/weather_forecasts/:location', to: 'weather_forecasts#show'
  get '/weather_forecasts', to: 'weather_forecasts#index'
end
``

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/weather_forecasts_controller.rb
class WeatherForecastsController < ApplicationController
  before_action :validate_params, only: [:show]

  def index
    if params[:location].present?
      redirect_to action: :show, location: params[:location]
    else
      # Default to New York's zip code
      redirect_to action: :show, location: '10281'
    end
  end

  def show
    @location = params[:location]
    @weather_data, @weather_data_cached, @weather_code_status = WeatherService.fetch_and_process_data(@location)
    forecast_data = WeatherForecastService.fetch_and_process_data(@location)
    @specific_weather_data_cached = forecast_data[:specific_weather_data_cached]
    @max_temperature = forecast_data[:max_temperature]
    @min_temperature = forecast_data[:min_temperature]
    @daily_weather_data = forecast_data[:specific_weather_data]["timelines"]["daily"]
    render 'show'
  end

  private

  def validate_params
    unless params[:location].present?
      redirect_to root_path, alert: 'Location parameter is missing'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weatherapp</title>
    <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'weather_forecasts_index', media: 'all', 'data-turbolinks-track': 'reload' if controller_name == 'weather_forecasts' && action_name == 'index' %>
  <%= stylesheet_link_tag 'weather_forecasts_show', media: 'all', 'data-turbolinks-track': 'reload' if controller_name == 'weather_forecasts' && action_name == 'show' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/3.6.95/css/materialdesignicons.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather_forecasts/show.html.erb
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <%= form_tag(weather_forecasts_path, method: "get", class: "zip-code-search-form") do %>
              <div class="form-group">
                <%= label_tag(:location, "Enter Zip Code Or City:", class: "form-label") %>
                <%= text_field_tag(:location, nil, placeholder: "e.g., 10281 or Delhi", class: "form-control") %>
              </div>
              <%= submit_tag("Search", class: "btn btn-primary") %>
            <% end %>
            <div class="col-lg-8 grid-margin stretch-card">
              <!--weather card-->
              <div class="card card-weather">
                <div class="card-body">
                  <div class="weather-date-location">
                    <h3><%= Date.today.strftime("%A") %></h3>
                    <p class="text-gray">
                      <span class="weather-date"><%= Date.today.strftime("%B %Y") %></span>
                      <span class="weather-location"><%= @weather_data["location"]["name"].split(",").second %>, <%= @location%></span>
                      <% if @weather_data_cached %>
                        <span class="cache-indicator">(Temperature Cached)</span>
                      <% end %>
                    </p>
                  </div>
                  <div class="weather-data d-flex">
                    <div class="mr-auto">
                      <h4 class="display-3"><%= @weather_data["data"]["values"]["temperature"].round %>
                        <span class="symbol">&deg;</span>C</h4>
                      <p class="text-gray">
                        <span>Max: <%= @max_temperature.round %>&deg;C</span> |
                        <span>Min: <%= @min_temperature.round %>&deg;C</span>
                      </p>
                      <p>
                        <%= @weather_code_status %> <!-- You might want to map this code to a condition -->
                        <% if @specific_weather_data_cached %>
                          <span class="cache-indicator">(Forecast Cached)</span>
                        <% end %>
                      </p>
                    </div>
                  </div>
                </div>
                <div class="card-body p-0">
                  <div class="d-flex weakly-weather">
                    <% @daily_weather_data.each do |forecast| %>
                    <div class="weakly-weather-item">
                      <p class="mb-0">
                        <%= forecast["time"].to_time.strftime("%a") %>
                      </p>
                      <i class="mdi mdi-weather-cloudy"></i> <!-- Adjust icon based on forecast["values"]["weatherCode"] -->
                      <p class="mb-0">
                        <%= forecast["values"]["temperatureAvg"].round %>&deg;
                      </p>
                      <small class="text-muted">
                        <%= forecast["values"]["temperatureMax"].round %>&deg; | <%= forecast["values"]["temperatureMin"].round %>&deg;
                      </small>
                    </div>
                    <% end %>
                  </div>
                </div>
              </div>
              <!--weather card ends-->
            </div>
        </div>
    </div>
</div>